name: Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install -g @vscode/vsce
      
      - name: Build
        run: npm run compile
        
      - name: Package Extension
        run: vsce package
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: "*.vsix"

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix-package
          
      - name: Publish to Visual Studio Marketplace
        run: |
          npx vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}